// export/docx.ts — Real DOCX via the `docx` library. Lazy-loaded chunk.
import { splitByHeadings } from "../markdown/sections.ts";
import { safeFilename, triggerDownload } from "./filename.ts";

export async function exportDocxFile(title: string, docType: string, doc: string): Promise<void> {
  const { Document, Packer, Paragraph, HeadingLevel, TextRun, AlignmentType } = await import("docx");

  const children: InstanceType<typeof Paragraph>[] = [];

  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.START,
      children: [new TextRun({ text: title, bold: true })],
    }),
  );
  children.push(new Paragraph({ children: [new TextRun({ text: docType, italics: true, color: "666666" })] }));
  children.push(new Paragraph({ text: "" }));

  const blocks = splitByHeadings(doc);
  for (const b of blocks) {
    if (b.type === "h1" && b.text) {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: b.text, bold: true })] }));
      continue;
    }
    if (b.type === "section" && b.heading) {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: b.heading, bold: true })] }));
    }
    const lines = b.content.split("\n");
    for (const raw of lines) {
      const l = raw.trim();
      if (!l) {
        children.push(new Paragraph({ text: "" }));
        continue;
      }
      if (/^[-*]\s+/.test(l)) {
        children.push(new Paragraph({ text: l.replace(/^[-*]\s+/, ""), bullet: { level: 0 } }));
      } else if (/^\d+\.\s+/.test(l)) {
        children.push(new Paragraph({ text: l.replace(/^\d+\.\s+/, ""), numbering: { reference: "default-numbering", level: 0 } }));
      } else if (/^#{3,6}\s+/.test(l)) {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: l.replace(/^#{3,6}\s+/, ""), bold: true })] }));
      } else if (l.startsWith("> ")) {
        children.push(new Paragraph({ children: [new TextRun({ text: l.slice(2), italics: true, color: "555555" })] }));
      } else {
        children.push(new Paragraph({ children: [new TextRun({ text: l.replace(/[*_`]/g, "") })] }));
      }
    }
  }

  const document = new Document({
    creator: "Architectly",
    title,
    description: `${docType} generated by Architectly`,
    numbering: {
      config: [
        {
          reference: "default-numbering",
          levels: [{ level: 0, format: "decimal", text: "%1.", alignment: AlignmentType.START }],
        },
      ],
    },
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(document);
  triggerDownload(safeFilename(title, "docx"), blob, "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
}
