// export/html.ts — Standalone, styled HTML export.
import { renderMarkdown } from "../markdown/render.ts";
import { safeFilename, triggerDownload } from "./filename.ts";

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => {
    switch (c) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      default:
        return "&#39;";
    }
  });
}

export function buildStandaloneHtml(
  title: string,
  docType: string,
  doc: string,
  date: string,
  dir: "ltr" | "rtl",
  lang: string,
): string {
  const body = renderMarkdown(doc);
  return `<!doctype html>
<html lang="${escapeHtml(lang)}" dir="${dir}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)} — ${escapeHtml(docType)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body { font: 16px/1.7 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 820px; margin: 48px auto; padding: 0 24px; color: #121212; background: #fff; }
  h1 { font-size: 2.1rem; margin: 0 0 1rem; border-bottom: 2px solid #1DB954; padding-bottom: .6rem; font-weight: 800; letter-spacing: -.02em; }
  h2 { font-size: 1.4rem; margin: 2rem 0 .8rem; color: #0a0a0a; border-bottom: 1px solid #e5e5e5; padding-bottom: .4rem; }
  h3 { font-size: 1.1rem; margin: 1.25rem 0 .5rem; color: #1a1a1a; }
  p { margin: .6rem 0; }
  ul, ol { padding-inline-start: 1.5rem; margin: .5rem 0; }
  li { margin: .3rem 0; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: .95rem; }
  th, td { border: 1px solid #ddd; padding: .55rem .8rem; text-align: start; vertical-align: top; }
  th { background: #f6f6f6; font-weight: 600; }
  code { background: #f1f1f1; padding: .1em .35em; border-radius: 4px; font-size: .9em; }
  pre { background: #0a0a0a; color: #f5f5f5; padding: 1rem; border-radius: 8px; overflow: auto; font-size: .9em; }
  pre code { background: transparent; color: inherit; padding: 0; }
  blockquote { border-inline-start: 3px solid #1DB954; background: #f0fdf4; margin: 1rem 0; padding: .6rem 1rem; border-radius: 0 6px 6px 0; }
  hr { border: none; border-top: 1px solid #e5e5e5; margin: 2rem 0; }
  @media (prefers-color-scheme: dark) {
    body { background: #121212; color: #e8e8e8; }
    h1, h2, h3 { color: #f5f5f5; }
    h2 { border-color: #2a2a2a; }
    th { background: #1e1e1e; }
    th, td { border-color: #2a2a2a; }
    code { background: #1e1e1e; color: #e8e8e8; }
    blockquote { background: #0d2818; }
  }
  @media print { body { max-width: 100%; margin: 0; padding: 24px; } h1, h2, h3 { page-break-after: avoid; } table, figure { page-break-inside: avoid; } }
</style>
</head>
<body>
${body}
<footer style="margin-top:3rem;color:#666;font-size:.85rem;border-top:1px solid #e5e5e5;padding-top:1rem">
Generated by Architectly · ${escapeHtml(date)}
</footer>
</body>
</html>`;
}

export function exportHtmlFile(
  title: string,
  docType: string,
  doc: string,
  date: string,
  dir: "ltr" | "rtl",
  lang: string,
): void {
  const html = buildStandaloneHtml(title, docType, doc, date, dir, lang);
  triggerDownload(safeFilename(title, "html"), html, "text/html;charset=utf-8");
}
